/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/
/*                                                      */
/* File:  AR3_020720.h                                  */
/*                                                      */
/* Author: Automatically generated by Xfuzzy            */
/*                                                      */
/*++++++++++++++++++++++++++++++++++++++++++++++++++++++*/

#ifndef XFUZZY
#define XFUZZY
/*------------------------------------------------------*/
/* Fuzzy Number                                         */
/*------------------------------------------------------*/

 typedef struct {
   double (* equal)(double x);
   double (* center)();
   double (* basis)();
   double (* param)(int i);
 } Consequent;

 typedef struct {
   double min;
   double max;
   double step;
   double (* imp)(double a, double b);
   double (* also)(double a, double b);
   int length;
   double* degree;
   int inputlength;
   double* input;
   Consequent* conc;
 } FuzzyNumber;

#endif /* XFUZZY */


#ifndef XFUZZY_AR3_020720
#define XFUZZY_AR3_020720
/*------------------------------------------------------*/
/* Inference Engine                                     */
/*------------------------------------------------------*/

void AR3_020720InferenceEngine(double AR1, double AR2, double AR3, double AR4, double AR5, double AR6, double AR7, double AR8, double AR9, double AR10, double AR11, double AR12, double AR13, double AR14, double AR15, double AR16, double AR17, double AR18, double AR19_2, double* Vulnerability, double* Risks, double* Functional_Service_Life);

#endif /* XFUZZY_AR3_020720 */
